live_config_reload = true

[window]
padding = { x = 4, y = 4 }
dimensions = { columns = 100, lines = 25 }
dynamic_padding = true
decorations = "Buttonless"
resize_increments = true
opacity = 0.8
option_as_alt = "Both"

## Colors

[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

## Fonts

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[cursor]
style = { blinking = "On" }

## Keybinds
# TODO: https://alacritty.org/config-alacritty-bindings.html
# disable default keybinds

[[keyboard.bindings]]
key = "N"
mods = "Control"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Q"
mods = "Control"
action = "Quit"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "T"
mods = "Control"
action = "CreateNewTab"

[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "="
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "="
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "H"
mods = "Control"
action = "Hide"

[[keyboard.bindings]]
key = "H"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Command|Control"
action = "None"
