[[mac]]
names = [
  "nvim",
  "alacritty",
  "fish",
  "yabai",
  "zellij",
  "lazygit",
  "sketchybar",
  "skhd",
]
to = "~/.config"

[[mac]]
name = "hammerspoon"
to = "~/"
rename = ".hammerspoon"

[[mac]]
name = ".gitconfig"
to = "~/"

[[fedora]]
names = ["fish", "nvim", "lazygit"]
to = "~/.config"

# Common linux configs
[[linux]]
names = ["fish"]
to = "~/.config"
