[[macOS]]
names = [
  "nvim",
  "alacritty",
  "fish",
  "yabai",
  "zellij",
  "lazygit",
  "sketchybar",
  "xplr",
  "lazyvim",
]
to = "~/.config"

[[macOS]]
name = "hammerspoon"
to = "~/"
rename = ".hammerspoon"

[[macOS]]
name = ".gitconfig"
to = "~/"

[[linux]]
names = []
to = "~/.config"
