#!/bin/bash

# run `man yabai` to check out all the configs

# for start without password
# check out `https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition`
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# enable debug mode
# yabai -m config debug_output on

# Global Settings
# ###################
# Layout
yabai -m config layout bsp

yabai -m config external_bar all:32:0

# Window
#
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
# Newly created window will be managed in where it was created
yabai -m config window_origin_display default
# Duration of transition between active / normal opacity
yabai -m config window_opacity_duration 0.0
# Enable opacity for windows
yabai -m config window_opacity on
# Don't draw shadow for windows
yabai -m config window_shadow off
# Don't blance the window occupy
yabai -m config auto_balance off
# Padding
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# Mouse
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
# Keyboard modifier used for moving and resizing windows
yabai -m config mouse_modifier fn
# Left click hold
yabai -m config mouse_action1 move
# Right click hold
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# Space Settings
# ##############
# yabai -m config --space 3 layout stack

# Make the below apps transparent when unfocused
APP_LIST="(Spotify|Alacritty|Chrome|Code|Poe|Obsidian)"

yabai -m signal --add event=window_focused app="^${APP_LIST}$" action="yabai -m config active_window_opacity 0.9"
yabai -m signal --add event=window_focused app="^${APP_LIST}$" action="yabai -m config normal_window_opacity 0.7"
#

# When any other app gains focus, reset both active and background window opacity to fully visible
# yabai -m signal --add event=window_focused app!="^${APP_LIST}$" action="yabai -m config active_window_opacity 1.0"
# yabai -m signal --add event=window_focused app!="^${APP_LIST}$" action="yabai -m config normal_window_opacity 1.0"

EXCLUDED_APPS="(System Settings|iStat Menus|Raycast|Calculator|Hammerspoon|BetterDisplay|GIMP|Notes|Hyperkey|KeyCastr)"
yabai -m rule --add app="^${EXCLUDED_APPS}$" manage=off

# See https://github.com/FelixKratz/JankyBorders?tab=readme-ov-file#bootstrap-with-yabai
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &
