- name: Install fd on macOS
  when: asnible_facts['os_family'] == 'Darwin'
  community.general.homebrew:
    name: fd
    state: present
- name: Install fd on Fedora Linux
  when: ansible_facts['distro'] == 'Fedora'
  ansible.builtin.dnf:
    name: fd
    state: latest
